#!/bin/bash -e

ORG_PATH=github.com/nodetemple
REPO_PATH=${ORG_PATH}/nodetemple

export GOPATH=${PWD}/gopath

rm -f ${GOPATH}/src/${REPO_PATH}
mkdir -p ${GOPATH}/src/${ORG_PATH}
ln -s ${PWD} ${GOPATH}/src/${REPO_PATH}

git clone https://github.com/spf13/cobra.git ${GOPATH}/src/github.com/spf13/cobra

eval $(go env)

#echo "Building noded..."
#CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-s' -o bin/noded ${REPO_PATH}/noded

echo "Building nodectl..."
CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-s' -o bin/nodectl ${REPO_PATH}/nodectl
